### ISSUE TITLE
Survivor Wikipedia entry

### ISSUE THREAD

**Issue by wonea** [scottschiller/SURVIVOR#2]
I'm working on http://osgameclones.com/ trying to build a list of open source clones of games. I've added your game and created a Wikipedia page for the original game to reference. The Wikipedia page needs fleshing out a little more, is there any chance you could provide a technical background to the game or contribute anything else you know.

https://en.wikipedia.org/wiki/Survivor_(1982_video_game)

**Comment by scottschiller** [comment]
Thanks for the note; sorry I don't have much detail on the history of this game, a boxed version or similar for screenshots etc. (Side note: I should fix that. :smile:)

One link that does have some details, box art and such that may be of interest -
https://www.c64-wiki.com/index.php/Survivor

I also did a write-up on the game myself, though my analysis was based simply on playing the original and making notes for the purpose of the remake.
http://www.schillmania.com/content/entries/2012/survivor-c64-html-remake/

**Comment by scottschiller** [comment]
While I've got your attention, you might also like Armor Alley which I've also done in similar style.
http://www.schillmania.com/content/entries/2013/armor-alley-web-prototype/
https://github.com/scottschiller/ArmorAlley
http://schillmania.com/armor-alley/

**Comment by wonea** [comment]
Thanks for the extra information. I've also added Armor Alley, thanks for tip.

https://github.com/wonea/osgameclones/commit/55150ecb486894daa9cdbd1776e0306087ef6f47

**Comment by scottschiller** [comment]
:+1:
